name: Trigger Jenkins Build

on:
  push:
    branches:
      - main

jobs:
  call-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Remote Build
        run: |
          JENKINS_URL="http://111.125.193.102:8080"
          JOB="GitHub CICD Using GItHub Actions"
          TOKEN="117820228e0c5831e55cf24a9f1add697f"
          USER="Anisha"

          curl -X POST \
            "$JENKINS_URL/job/$JOB/build" \
            --user "$USER:$TOKEN"
